Unit -3 Feature Creation & Feture Transformation

to convert categorical column to numerical column

In [2]:
import pandas as pd
import plotly.express as px
data={'marks':[40,41,42,44,42,43,41,48,49,45,46,48],
     'gender':['M','F','M','M','F','M','M','F','F','F','M','M']}
df=pd.DataFrame(data)
df

    marks gender
0      40      M
1      41      F
2      42      M
3      44      M
4      42      F
5      43      M
6      41      M
7      48      F
8      49      F
9      45      F
10     46      M
11     48      M

In [4]:
pd.get_dummies(df,drop_first=True)

    marks  gender_M
0      40      True
1      41     False
2      42      True
3      44      True
4      42     False
5      43      True
6      41      True
7      48     False
8      49     False
9      45     False
10     46      True
11     48      True

Feture creation

In [7]:
import numpy as np
df['result']=np.where(df['marks']>43,'pass','fail')
df

    marks gender result
0      40      M   fail
1      41      F   fail
2      42      M   fail
3      44      M   pass
4      42      F   fail
5      43      M   fail
6      41      M   fail
7      48      F   pass
8      49      F   pass
9      45      F   pass
10     46      M   pass
11     48      M   pass

In [12]:
df['grade']=np.where(df['marks']>47,'A',
                     np.where(df['marks']>45,'B',
                     np.where(df['marks']>43,'C','D')))
df

    marks gender result grade
0      40      M   fail     D
1      41      F   fail     D
2      42      M   fail     D
3      44      M   pass     C
4      42      F   fail     D
5      43      M   fail     D
6      41      M   fail     D
7      48      F   pass     A
8      49      F   pass     A
9      45      F   pass     C
10     46      M   pass     B
11     48      M   pass     A

Arithmetic Operation

In [13]:
data={'A':[10,20,15,12],
     'B':[40,42,44,45]}
df=pd.DataFrame(data)
df['A']+2

0    12
1    22
2    17
3    14
Name: A, dtype: int64

In [14]:
df['A']/df['B']

0    0.250000
1    0.476190
2    0.340909
3    0.266667
dtype: float64

Train validation Split

In [16]:
from sklearn.model_selection import train_test_split

In [18]:
import pandas as pd
import plotly.express as px
data={'marks':[40,41,42,44,42,43,41,48,49,45,46,48],
     'gender':['M','F','M','M','F','M','M','F','F','F','M','M']}
df=pd.DataFrame(data)
x=df['gender']
y=df['marks']